### ISSUE TITLE
awesome 4.0 breaking changes

### ISSUE THREAD

**Issue by AndreiUlmeyda** [dodo/uzful#6]
Hi there, I've got the following error
`error: /usr/share/awesome/lib/uzful/widget/span.lua:10: module 'wibox.layout.base' not found: ...`
then again, awesome released a major version.
In the best case it's just some module renaming.

[awesome change doc](https://awesomewm.org/apidoc/documentation/89-NEWS.md.html#v4)

Cheerio

**Comment by blastmaster** [comment]
yeah, this is easy, just use ```wibox.widget.base``` instead of ```wibox.layout.base``` this has changed since  
[3338718b9](https://github.com/awesomeWM/awesome/commit/3338718b9324e463e3ed87f9eeba1d07fc8c4114).
But I'am afraid that this is not the end of the road.
